### ISSUE TITLE
android-sdk-update failed on JDK 11

### ISSUE THREAD

**Issue by doniwinata0309** [bitrise-io/bitrise-steplib#3125]
When using JDK 11, android-sdk-update step failed with this stacktrace:
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	
Do you have plan to fix this error on this step ? thank you in advance

**Comment by ofalvai** [comment]
Hello @doniwinata0309 👋 

This is unfortunately a limitation of the Android SDK, some tools (such as `sdkmanager`) are not yet compatible with JDK 11 at the moment and need JDK 8 to run correctly. What you can do is change the order of your workflow steps to only enable JDK 11 after your failing step. For more details, see this guide: https://support.bitrise.io/hc/en-us/articles/360017059718

**Comment by doniwinata0309** [comment]
ah got it, thanks for the link
