### ISSUE TITLE
[xcode-archive] fails at fetching devices if some are in the state "Ineligible for x days"

### ISSUE THREAD

**Issue by aaachris** [bitrise-io/bitrise-steplib#3791]
Some of my iOS devices are in the state "Ineligible for x days" at:
https://developer.apple.com/account/resources/devices/list

<img width="265" alt="Screenshot 2023-04-04 at 13 35 01" src="https://user-images.githubusercontent.com/6814605/229779300-fa30b4a5-bb8a-436f-b47e-3bb4f0bb3b2b.png">

```
Fetching Apple Developer Portal devices
Failed to execute Step main logic:
  failed to manage code signing: failed to ensure test devices: failed to fetch devices: failed to query Developer Portal: invalid device status p, stacktrace: /private/var/folders/dw/lz_9l61x0y9089f673sqt55h0000gn/T/2230338121/devices.rb:63:in `map_device_status_to_api_status'
  /private/var/folders/dw/lz_9l61x0y9089f673sqt55h0000gn/T/2230338121/devices.rb:15:in `block in list_devices'
  /private/var/folders/dw/lz_9l61x0y9089f673sqt55h0000gn/T/2230338121/devices.rb:8:in `each'
  /private/var/folders/dw/lz_9l61x0y9089f673sqt55h0000gn/T/2230338121/devices.rb:8:in `list_devices'
  main.rb:63:in `<main>'
```

It seems like it's only a mapping issue: `map_device_status_to_api_status` 
Locally I can create an archive with Xcode (14.2) therefore I think it should be possible on bitrise as well.

**Comment by dwolfand** [comment]
We are having this same issue when adding new devices that are in the "Processing" status. 
<img width="469" alt="image" src="https://github.com/bitrise-io/bitrise-steplib/assets/4984975/8d7eff36-f02d-48aa-b77c-abc40be56954">

**Comment by Badlazzor** [comment]
Hi @chrisgblr,

Apologies for the long silence on this one — we're doing a backlog-cleanup pass on this repo and closing items that have been inactive for a while (1149 days here) and likely no longer reflect the current state of the tooling.

If this is still a problem on the latest version, please re-open with a fresh repro and we'll take another look. Thanks for the original report.
